### ISSUE TITLE
TypeError: undefined is not a function at rd.f.$setPristine

### ISSUE THREAD

**Issue by maxipeli** [jrief/django-angular#153]
Hi!

  Great Job with django-angular!
  I have a little issue, I upgrade my angularjs from 1.2.6 to 1.3.13, but now I'm getting everytime this error:
 ```javascript
TypeError: undefined is not a function
    at rd.f.$setPristine (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:151:453)
    at link (http://localhost:8000/static/js/ng-django-forms.js:134:13)
    at $ (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:70:149)
    at v (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:59:203)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:51:299)
    at v (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:59:147)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:51:299)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:51:316)
    at v (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:59:147)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:51:299) <input class="form-control ng-untouched ng-valid ng-dirty ng-valid-required ng-valid-minlength ng-valid-maxlength" id="id_name" maxlength="20" name="name" ng-maxlength="20" ng-minlength="3" ng-model="childform.name" ng-required="true" type="text" value="cuadradito"> 
```
The form is working perfectly, but on console I see the error.

I hope somebody can help me..

Thanks!

**Comment by jrief** [comment]
Is this project online somewhere, so that I can see that?
(If its a non-public staging system, don't hesitate so send me the URL via email).

**Comment by maxipeli** [comment]
Everything's working now!
 
   I was coding an example to pass you the url, then I could see that the error is for ngAnimate, I was using 1.2.0 and it was creating an conflict, so I've changed to 1.3.0 and everything is fine.

  I'm sorry for creating this issue,  django-angular works perfect for me!

Thanks
