### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'custom_arg1'

### ISSUE THREAD

**Issue by andrey-oparin** [jrief/django-angular#195]
Hi, i create simple unit test which describes the problem with custom arguments in Form constructor. Check pull request #187 

```python
class CustomArgsForm(forms.Form):
    field1 = forms.CharField(widget=forms.HiddenInput)
    field2 = forms.CharField(widget=forms.HiddenInput)

    def __init__(self, custom_arg1=None, custom_arg2=None, *args, **kwargs):
        self.custom_arg1 = custom_arg1
        self.custom_arg2 = custom_arg2
        super(CustomArgsForm, self).__init__(*args, **kwargs)


class NgCustomArgsForm(six.with_metaclass(NgDeclarativeFieldsMetaclass, NgFormValidationMixin, CustomArgsForm)):
    pass

class NgModelFormMixinTest(TestCase):
    valid_data = {
        'email': 'john@example.com',
        'onoff': True,
        'sex': 'f',
        'select_multi': ['a', 'd'],
        'check_multi': ['b', 'c'],
        'sub1': {
            'select_choices': 'c',
            'radio_choices': 'c',
            'first_name': 'Susan',
        },
        'sub2': {
            'select_choices': 'b',
            'radio_choices': 'a',
        },
        'hide_me': 'hidden string',
    }

    def setUp(self):
        # create an unbound form
        self.unbound_form = DummyForm()
        htmlsource = self.unbound_form.as_p() + self.unbound_form.sub1.as_p() + self.unbound_form.sub2.as_p()
        self.dom = PyQuery(htmlsource)
        self.elements = self.dom('input') + self.dom('select')

    def test_form_with_custom_args(self):
        form_post_data = {'field1': 'value1', 'field2': 'value2'}

        custom_args_form = CustomArgsForm(data=form_post_data, custom_arg1=1, custom_arg2=2)
        custom_args_form.full_clean()

        self.assertEqual(form_post_data, custom_args_form.data, 'lost data')
        self.assertEqual(custom_args_form.cleaned_data.get('field1'), 'value1', 'lost field1 value')
        self.assertEqual(custom_args_form.cleaned_data.get('field2'), 'value2', 'lost field2 value')
        self.assertEqual(1, custom_args_form.custom_arg1, 'lost custom arg1')
        self.assertEqual(2, custom_args_form.custom_arg2, 'lost custom arg2')

        ng_custom_args_form = NgCustomArgsForm(data=form_post_data, custom_arg1=1, custom_arg2=2)
        ng_custom_args_form.full_clean()

        self.assertEqual(form_post_data, ng_custom_args_form.data, 'lost data')
        self.assertEqual(ng_custom_args_form.cleaned_data.get('field1'), 'value1', 'lost field1 value')
        self.assertEqual(ng_custom_args_form.cleaned_data.get('field2'), 'value2', 'lost field2 value')
        self.assertEqual(1, ng_custom_args_form.custom_arg1, 'lost custom arg1')
        self.assertEqual(2, ng_custom_args_form.custom_arg2, 'lost custom arg2')
```

Test failed with following error:
ERROR: test_form_with_custom_args (server.tests.test_forms.NgModelFormMixinTest)

Traceback (most recent call last):
File "/home/travis/build/jrief/django-angular/examples/server/tests/test_forms.py", line 128, in test_form_with_custom_args
ng_custom_args_form = NgCustomArgsForm(data=form_post_data, custom_arg1=1, custom_arg2=2)
File "/home/travis/build/jrief/django-angular/djangular/forms/angular_validation.py", line 17, in init
super(NgFormValidationMixin, self).init(args, *kwargs)
File "/home/travis/build/jrief/django-angular/djangular/forms/angular_base.py", line 242, in init
super(NgFormBaseMixin, self).init(data, args, *kwargs)
TypeError: init() got multiple values for keyword argument 'custom_arg1'

Ran 57 tests in 0.509s
FAILED (errors=1)

**Comment by andrey-oparin** [comment]
and fix it, check pull request #195

**Comment by andrey-oparin** [comment]
Hi, i describe about problem with custom form args more than 5 days ago and provide solution, you check issues ?

**Comment by jrief** [comment]
This can have a ton of side effects. If I expect the ``data`` as an *arg and not as an **kwarg it presumably is for good reason (although I don't remember which).

**Comment by andrey-oparin** [comment]
Ok, maybe my solution is wrong, but current version django angular does not work with form with custom args. You can check it with my unit test.

```python
super(NgFormBaseMixin, self).__init__(data, *args, **kwargs) # it throws TypeError: init() got multiple values for keyword argument if form have cusom arguments
```
I think you can also fix this in the following way:

```python
kwargs.update(data=data)
super(NgFormBaseMixin, self).__init__(*args, **kwargs)
```
