### ISSUE TITLE
How to disable ng-forms on some view? 

### ISSUE THREAD

**Issue by iho** [jrief/django-angular#240]
I have editable table with lot of forms (50) and this plugin trying convert it all fields
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at u (http://localhost:8000/static/vendor/select.min.js:7:8346)
    at g.parseRepeatAttr (http://localhost:8000/static/vendor/select.min.js:7:8457)
    at http://localhost:8000/static/vendor/select.min.js:7:3443
    at ca (http://localhost:8000/static/vendor/angular.min.js:73:279)
    at I (http://localhost:8000/static/vendor/angular.min.js:62:174)
    at http://localhost:8000/static/vendor/angular.min.js:69:333
    at g (http://localhost:8000/static/vendor/angular.min.js:55:97)
    at http://localhost:8000/static/vendor/angular.min.js:54:239
    at http://localhost:8000/static/vendor/angular.min.js:56:79 <ul class="ui-select-choices ui-select-choices-content ui-select-dropdown dropdown-menu" role="listbox" ng-show="$select.items.length >
```

**Comment by jrief** [comment]
closed, because this bug can not be reproduced.

**Comment by adrienbrunet** [comment]
If your problem persists, please provide more context, a failing test or a way to reproduce it..
