### ISSUE TITLE
Getting error 'ImportError: No module named djng'

### ISSUE THREAD

**Issue by amitasthana** [jrief/django-angular#318]
pwd
/Users/amitasthana/awesto/django-angular/examples
(awesto) Amits-MacBook-Pro:examples amitasthana$ python manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x10608b578>
Traceback (most recent call last):
  File "/Users/amitasthana/awesto/awesto/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Users/amitasthana/awesto/awesto/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Users/amitasthana/awesto/awesto/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/amitasthana/awesto/awesto/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Users/amitasthana/awesto/awesto/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/amitasthana/awesto/awesto/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/amitasthana/awesto/awesto/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named djng

**Comment by jrief** [comment]
```
cd django-angular
pip install .
```

should fix it.
