### ISSUE TITLE
karma tests fail for Chrome and Firefox

### ISSUE THREAD

**Issue by fabiomontefuscolo** [jrief/django-angular#92]
I'm running an Archlinux, `grunt` at version 0.4.5 and `node` at 0.10.29. I have only Firefox and Chrome installed here and I got some errors after run tests. 

```
➜  client git:(f77a486) grunt test-all
Running "jshint:files" (jshint) task
>> 5 files lint free.

Running "karma:test-all" (karma) task
INFO [karma]: Karma v0.12.21 server started at http://localhost:9090/
WARN [launcher]: Can not load "Safari", it is not registered!
  Perhaps you are missing some plugin?
INFO [launcher]: Starting browser Chrome
INFO [launcher]: Starting browser ChromeCanary
INFO [launcher]: Starting browser Firefox
WARN [launcher]: Can not load "Opera", it is not registered!
  Perhaps you are missing some plugin?
ERROR [launcher]: Cannot start ChromeCanary
	Can not find the binary google-chrome-canary
	Please set env variable CHROME_CANARY_BIN
INFO [Chrome 36.0.1985 (Linux)]: Connected on socket -WyzDDeCDrRro3kCfZZa with id 27160550
INFO [Firefox 30.0.0 (Linux)]: Connected on socket l-w0GclaIiKT44vxfZZb with id 26534448
.....
Chrome 36.0.1985 (Linux) unit tests for module ng.django.forms test directive validateDate to accept 2014-04-01 FAILED
	Expected false to be true.
	Error: Expected false to be true.
	    at null.<anonymous> (/home/fabio/devel/django-angular/client/tests/djangoFormsSpec.js:96:35)
Chrome 36.0.1985 (Linux) unit tests for module ng.django.forms test directive validateDate to reject 2014-04-31 FAILED
	Expected true to be false.
	Error: Expected true to be false.
	    at null.<anonymous> (/home/fabio/devel/django-angular/client/tests/djangoFormsSpec.js:102:35)
..................
Chrome 36.0.1985 (Linux): Executed 25 of 25 (2 FAILED) (0.131 secs / 0.124 secs)
.....
Firefox 30.0.0 (Linux) unit tests for module ng.django.forms test directive validateDate to accept 2014-04-01 FAILED
	Expected false to be true.
	@/home/fabio/devel/django-angular/client/tests/djangoFormsSpec.js:96:4
	
...................
Firefox 30.0.0 (Linux): Executed 25 of 25 (1 FAILED) (0.112 secs / 0.103 secs)
TOTAL: 3 FAILED, 47 SUCCESS
Warning: Task "karma:test-all" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by adrienbrunet** [comment]
As far as I can tell, this is fixed now right? (I'm not on a mac so I can't test on safary but test passes for me on Ff and Chrome)

We do have some warnings via jshint though..
Closing this.
